import {
  Activity,
  ArrowLeft,
  Bell,
  Bluetooth,
  CalendarDays,
  ChartColumnBig,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  Clock,
  Dumbbell,
  Ellipsis,
  Hand,
  House,
  Lightbulb,
  MoreVertical,
  Play,
  Plus,
  Repeat,
  Search,
  SlidersHorizontal,
  Trash2,
  TriangleAlert,
  User,
  Users,
  Wifi,
  X,
  type LucideIcon,
} from 'lucide-react-native';

export const ICONS = {
  activity: Activity,
  arrowLeft: ArrowLeft,
  bell: Bell,
  bluetooth: Bluetooth,
  calendarDays: CalendarDays,
  chart: ChartColumnBig,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleCheck: CircleCheck,
  clock: Clock,
  dumbbell: Dumbbell,
  ellipsis: Ellipsis,
  hand: Hand,
  house: House,
  lightbulb: Lightbulb,
  moreVertical: MoreVertical,
  play: Play,
  plus: Plus,
  repeat: Repeat,
  search: Search,
  slidersHorizontal: SlidersHorizontal,
  triangleAlert: TriangleAlert,
  trash: Trash2,
  user: User,
  users: Users,
  wifi: Wifi,
  x: X,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
