import {
  Accessibility,
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Bell,
  Bluetooth,
  CalendarDays,
  ChartColumnBig,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  ClipboardList,
  Clock,
  Dumbbell,
  Ellipsis,
  Fingerprint,
  Globe,
  Grip,
  Hand,
  History,
  House,
  Image as ImageIcon,
  Lightbulb,
  Laptop,
  List,
  Lock,
  LogOut,
  MapPin,
  Monitor,
  MonitorSmartphone,
  MoreVertical,
  Move,
  Pencil,
  PersonStanding,
  Play,
  Plus,
  RefreshCcw,
  Repeat,
  Repeat2,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sun,
  Tablet,
  Trash2,
  TriangleAlert,
  Type,
  User,
  Users,
  Wifi,
  X,
  type LucideIcon,
} from 'lucide-react-native';

export const ICONS = {
  accessibility: Accessibility,
  activity: Activity,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  bell: Bell,
  bluetooth: Bluetooth,
  calendarDays: CalendarDays,
  chart: ChartColumnBig,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleCheck: CircleCheck,
  clipboard: ClipboardList,
  clock: Clock,
  dumbbell: Dumbbell,
  edit: Pencil,
  ellipsis: Ellipsis,
  fingerprint: Fingerprint,
  globe: Globe,
  grip: Grip,
  hand: Hand,
  history: History,
  house: House,
  image: ImageIcon,
  lightbulb: Lightbulb,
  laptop: Laptop,
  list: List,
  lock: Lock,
  logOut: LogOut,
  mapPin: MapPin,
  monitor: Monitor,
  monitorSmartphone: MonitorSmartphone,
  moreVertical: MoreVertical,
  move: Move,
  personStanding: PersonStanding,
  play: Play,
  plus: Plus,
  refreshCcw: RefreshCcw,
  repeat: Repeat,
  repeat2: Repeat2,
  search: Search,
  settings: Settings,
  shield: Shield,
  shieldCheck: ShieldCheck,
  slidersHorizontal: SlidersHorizontal,
  smartphone: Smartphone,
  sun: Sun,
  tablet: Tablet,
  triangleAlert: TriangleAlert,
  trash: Trash2,
  type: Type,
  user: User,
  users: Users,
  wifi: Wifi,
  x: X,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
